### ISSUE TITLE
Consider setting option "Report counts by strand" yes at default on Naive Variant Caller tool form

### ISSUE THREAD

**Issue by jennaj** [blankenberg/tools-blankenberg#4]
Variant Annotator expects a stranded VCF as input. Having this option default as "yes" for Naive Variant Caller would help reduce errors due to users not understanding usage requirements between the two tools.

**Comment by blankenberg** [comment]
Done in NVC version 0.0.4 56487ac8b5d91755e44d4e326105cdb9e409a66c
